version: "3"

services:
  create_movie:
    build:
      context: ./functions/create_complete_movie
      dockerfile: Dockerfile
    container_name: create_complete_movie_function
    environment:
      - CRED_PATH=/app/key.json
    volumes:
      - ./key.json:/app/key.json:ro
      - ./.env:/app/.env:ro

  contract_proxy:
    build:
      context: ./functions/contract_proxy
      dockerfile: Dockerfile
    container_name: contract_proxy_server
    volumes:
      - ./.env:/contract_proxy/.env:ro
    ports:
      - "8080:8080"
