version: "3"

services:
  create_movie:
    build:
      context: ./functions/create_complete_movie
      dockerfile: Dockerfile
    container_name: create_complete_movie_function
    environment:
      - CRED_PATH=/app/key.json
      - FONT_NAME=ipaexg
    volumes:
      - ./key.json:/app/key.json:ro
